services:
  app:
    image: bloglist-front
    build:
      context: ./bloglist-front
      dockerfile: Dockerfile
    container_name: bloglist-front

  server:
    image: bloglist-back
    build:
      context: ./bloglist-back
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: mongodb://bloglist_db_username:bloglist_db_password@mongo:27017/blogList
    container_name: bloglist-back

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: bloglist_db_username
      MONGO_INITDB_ROOT_PASSWORD: bloglist_db_password
      MONGO_INITDB_DATABASE: blogList
    volumes:
      - ./bloglist-back/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_bloglist_data:/data/db

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy-prod
    depends_on:
      - app

volumes:
  mongo_bloglist_data:
