services:
  app:
    image: todo-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-front

  server:
    image: todo-back
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    container_name: todo-back

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy-prod
    depends_on:
      - app

volumes:
  mongo_data:
  redis_data:
